---
- name: "check for existence of composer.json"
  stat: path="/var/www/{{ symfony_website_domain_name }}/composer.json"
  register: composer_json_file_exists

- name: "run composer install"
  command: composer install --ignore-platform-reqs
  args:
    chdir: "{{ symfony_project_root }}"
  when: composer_json_file_exists.stat.exists
