- name: symfony cache
  file: >
    path="{{ symfony_cache_path }}"
    state=directory
    owner="{{ symfony_web_server_user }}"
    group="{{ symfony_web_server_group }}"
    mode=0775
    recurse=true
  sudo: yes

- name: symfony acl - cache
  shell: >
    setfacl -R -m u:{{ symfony_web_server_user }}:rwX -m g:{{ symfony_web_server_group }}:rwX {{ symfony_cache_path }}
  sudo: yes

- name: symfony acl default - cache
  shell: >
    setfacl -dR -m u:{{ symfony_web_server_user }}:rwx -m g:{{ symfony_web_server_group }}:rwX {{ symfony_cache_path }}
  sudo: yes
