- name: symfony cache
  file: >
    path="{{ symfony_cache_path }}"
    state=directory
    owner="{{ nginx_user }}" group="{{ nginx_group }}"
    mode=0775
    recurse=true
  sudo: yes

- name: symfony acl 
  shell: >
    setfacl -R -m u:{{ nginx_user }}:rwX -m g:{{ nginx_group }}:rwX {{ symfony_cache_path }}
  sudo: yes

- name: symfony acl default 
  shell: >
    setfacl -dR -m u:{{ nginx_user }}:rwx -m g:{{ nginx_group }}:rwX {{ symfony_cache_path }}
  sudo: yes
