---
- include: nginx.yml
  when: "symfony2_web_server == 'nginx'"

- include: bash_completion.yml
  when: symfony2_bash_completion

- include: composer.yml
  when: symfony2_composer_install

- include: clear_cache.yml
  when: symfony2_clear_cache

- include: doctrine_schema_update.yml
  when: "symfony2_doctrine_schema_update != []"


- include: create_app_dir.yml
- include: create_cache.yml
- include: create_logs.yml