---
- name: "ensure directory for global nginx configuration files exists"
  file:
    path: /etc/nginx/global.d
    state: directory
  sudo: yes

- name: "ensure nginx site configuration is installed"
  template:
    src: nginx-vhost.conf.j2
    dest: "/etc/nginx/sites-available/{{ symfony_website_domain_name }}.conf"
  sudo: yes

- name: "ensure nginx site configuration is enabled"
  file:
    src: "/etc/nginx/sites-available/{{ symfony_website_domain_name }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ symfony_website_domain_name }}.conf"
    state: link
  sudo: yes
  notify: "restart web server"
